// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package movie

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SearchMovieServiceClient is the client API for SearchMovieService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchMovieServiceClient interface {
	SearchMovie(ctx context.Context, in *SearchMovieRequest, opts ...grpc.CallOption) (*SearchMovieResponse, error)
	GetMovieDetail(ctx context.Context, in *GetMovieDetailRequest, opts ...grpc.CallOption) (*GetMovieDetailResponse, error)
}

type searchMovieServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchMovieServiceClient(cc grpc.ClientConnInterface) SearchMovieServiceClient {
	return &searchMovieServiceClient{cc}
}

func (c *searchMovieServiceClient) SearchMovie(ctx context.Context, in *SearchMovieRequest, opts ...grpc.CallOption) (*SearchMovieResponse, error) {
	out := new(SearchMovieResponse)
	err := c.cc.Invoke(ctx, "/movie.SearchMovieService/SearchMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchMovieServiceClient) GetMovieDetail(ctx context.Context, in *GetMovieDetailRequest, opts ...grpc.CallOption) (*GetMovieDetailResponse, error) {
	out := new(GetMovieDetailResponse)
	err := c.cc.Invoke(ctx, "/movie.SearchMovieService/GetMovieDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchMovieServiceServer is the server API for SearchMovieService service.
// All implementations should embed UnimplementedSearchMovieServiceServer
// for forward compatibility
type SearchMovieServiceServer interface {
	SearchMovie(context.Context, *SearchMovieRequest) (*SearchMovieResponse, error)
	GetMovieDetail(context.Context, *GetMovieDetailRequest) (*GetMovieDetailResponse, error)
}

// UnimplementedSearchMovieServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSearchMovieServiceServer struct {
}

func (UnimplementedSearchMovieServiceServer) SearchMovie(context.Context, *SearchMovieRequest) (*SearchMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchMovie not implemented")
}
func (UnimplementedSearchMovieServiceServer) GetMovieDetail(context.Context, *GetMovieDetailRequest) (*GetMovieDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovieDetail not implemented")
}

// UnsafeSearchMovieServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchMovieServiceServer will
// result in compilation errors.
type UnsafeSearchMovieServiceServer interface {
	mustEmbedUnimplementedSearchMovieServiceServer()
}

func RegisterSearchMovieServiceServer(s grpc.ServiceRegistrar, srv SearchMovieServiceServer) {
	s.RegisterService(&SearchMovieService_ServiceDesc, srv)
}

func _SearchMovieService_SearchMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchMovieServiceServer).SearchMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/movie.SearchMovieService/SearchMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchMovieServiceServer).SearchMovie(ctx, req.(*SearchMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchMovieService_GetMovieDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMovieDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchMovieServiceServer).GetMovieDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/movie.SearchMovieService/GetMovieDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchMovieServiceServer).GetMovieDetail(ctx, req.(*GetMovieDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchMovieService_ServiceDesc is the grpc.ServiceDesc for SearchMovieService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchMovieService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "movie.SearchMovieService",
	HandlerType: (*SearchMovieServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchMovie",
			Handler:    _SearchMovieService_SearchMovie_Handler,
		},
		{
			MethodName: "GetMovieDetail",
			Handler:    _SearchMovieService_GetMovieDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "delivery/grpc/movie/movie.proto",
}
