// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package movie

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SearchMovieClient is the client API for SearchMovie service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchMovieClient interface {
	SearchMovie(ctx context.Context, in *SearchMovieRequest, opts ...grpc.CallOption) (*SearchMovieResponse, error)
	GetMovieDetail(ctx context.Context, in *GetMovieDetailRequest, opts ...grpc.CallOption) (*GetMovieDetailResponse, error)
}

type searchMovieClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchMovieClient(cc grpc.ClientConnInterface) SearchMovieClient {
	return &searchMovieClient{cc}
}

func (c *searchMovieClient) SearchMovie(ctx context.Context, in *SearchMovieRequest, opts ...grpc.CallOption) (*SearchMovieResponse, error) {
	out := new(SearchMovieResponse)
	err := c.cc.Invoke(ctx, "/movie.SearchMovie/SearchMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchMovieClient) GetMovieDetail(ctx context.Context, in *GetMovieDetailRequest, opts ...grpc.CallOption) (*GetMovieDetailResponse, error) {
	out := new(GetMovieDetailResponse)
	err := c.cc.Invoke(ctx, "/movie.SearchMovie/GetMovieDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchMovieServer is the server API for SearchMovie service.
// All implementations should embed UnimplementedSearchMovieServer
// for forward compatibility
type SearchMovieServer interface {
	SearchMovie(context.Context, *SearchMovieRequest) (*SearchMovieResponse, error)
	GetMovieDetail(context.Context, *GetMovieDetailRequest) (*GetMovieDetailResponse, error)
}

// UnimplementedSearchMovieServer should be embedded to have forward compatible implementations.
type UnimplementedSearchMovieServer struct {
}

func (UnimplementedSearchMovieServer) SearchMovie(context.Context, *SearchMovieRequest) (*SearchMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchMovie not implemented")
}
func (UnimplementedSearchMovieServer) GetMovieDetail(context.Context, *GetMovieDetailRequest) (*GetMovieDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovieDetail not implemented")
}

// UnsafeSearchMovieServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchMovieServer will
// result in compilation errors.
type UnsafeSearchMovieServer interface {
	mustEmbedUnimplementedSearchMovieServer()
}

func RegisterSearchMovieServer(s grpc.ServiceRegistrar, srv SearchMovieServer) {
	s.RegisterService(&SearchMovie_ServiceDesc, srv)
}

func _SearchMovie_SearchMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchMovieServer).SearchMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/movie.SearchMovie/SearchMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchMovieServer).SearchMovie(ctx, req.(*SearchMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchMovie_GetMovieDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMovieDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchMovieServer).GetMovieDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/movie.SearchMovie/GetMovieDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchMovieServer).GetMovieDetail(ctx, req.(*GetMovieDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchMovie_ServiceDesc is the grpc.ServiceDesc for SearchMovie service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchMovie_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "movie.SearchMovie",
	HandlerType: (*SearchMovieServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchMovie",
			Handler:    _SearchMovie_SearchMovie_Handler,
		},
		{
			MethodName: "GetMovieDetail",
			Handler:    _SearchMovie_GetMovieDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "delivery/grpc/movie/movie.proto",
}
