// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DummyDB is an autogenerated mock type for the DummyDB type
type DummyDB struct {
	mock.Mock
}

// Log provides a mock function with given fields: record
func (_m *DummyDB) Log(record string) error {
	ret := _m.Called(record)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
